### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by uwbadger84** [juliomalegria/python-craigslist#121]
I am using the Python Craigslist Headless code on a raspberry pi with a fresh installation of Bullseye.  Prior to using the headless fork, I had been using the Python Craigslist code.  When I try to execute my pre-existing code on the headless code, I receive the following error message.  Any help would be greatly appreciated.  Thanks, Vic

	2023-03-23 11:20:08,220 INFO     patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver

	2023-03-23 11:20:08,513 CRITICAL Terminating due to unexpected error: <class 'OSError'>

	2023-03-23 11:20:08,533 CRITICAL Traceback (most recent call last):

	  File "/usr/local/sbin/cl_alert.py", line 307, in main

	    cl_ads= CraigslistForSale(site=nationwide[i], category='moa', filters={'query': 'iphone', 'max_price': 150})

	  File "/usr/local/sbin/base.py", line 59, in __init__

	    self.browser = CraigslistBrowser()

	  File "/usr/local/sbin/browser.py", line 20, in __init__

	    self.driver = uc.Chrome(options=self._get_options())

	  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/__init__.py", line 441, in __init__

	    super(Chrome, self).__init__(

	  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__

	    super().__init__(

	  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__

	    self.service.start()

	  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 88, in start

	    self._start_process(self.path)

	  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 195, in _start_process

	    self.process = subprocess.Popen(

	  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

	    self._execute_child(args, executable, preexec_fn, close_fds,

	  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

	    raise child_exception_type(errno_num, err_msg, err_filename)

	OSError: [Errno 8] Exec format error: '/root/.local/share/undetected_chromedriver/undetected_chromedriver'

**Comment by khelms-sf** [comment]
hey I'm sorry I can't help with your issue, but I just read the other issue where a user introduces the headless fork. Can you confirm that works?

**Comment by uwbadger84** [comment]
Thanks for the reply.  I will try to contact the author of the headless fork to get resolution.
