### ISSUE TITLE
I'm having trouble running the example code :(

### ISSUE THREAD

**Issue by potofpie** [juliomalegria/python-craigslist#4]
C:\Python27\python.exe "C:/Users/Bobby/PycharmProjects/untitled/complicated loops.py"
Traceback (most recent call last):
  File "C:/Users/Bobby/PycharmProjects/untitled/complicated loops.py", line 2, in <module>
    from craigslist import CraigslistHousing
  File "C:\Python27\lib\site-packages\craigslist\__init__.py", line 4, in <module>
    import requests
  File "C:\Python27\lib\site-packages\requests\__init__.py", line 58, in <module>
    from . import utils
  File "C:\Python27\lib\site-packages\requests\utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\Python27\lib\site-packages\requests\compat.py", line 7, in <module>
    from .packages import chardet
  File "C:\Python27\lib\site-packages\requests\packages\__init__.py", line 3, in <module>
    from . import urllib3
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\__init__.py", line 10, in <module>
    from .connectionpool import (
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 37, in <module>
    from .request import RequestMethods
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\request.py", line 6, in <module>
    from .filepost import encode_multipart_formdata
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\filepost.py", line 8, in <module>
    from .fields import RequestField
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\fields.py", line 1, in <module>
    import email.utils
ImportError: No module named utils

Process finished with exit code 1

I installed the module via pip on my windows computer. It is in the list of modules when I do pip list. Do i have to access a setup file now or what?

**Comment by potofpie** [comment]
Never mind, don't forget to set the Path in environment variable on Windows.
